max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot
#obstacle_range: 2.5
#raytrace_range: 3.0
#inflation_radius: 0.55
#transform_tolerance: 0.5

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
#robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18) （圆形机器人设置远离障碍物距离）

# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular（如果机器人不是圆的设置这个）
footprint: [[-0.21, -0.21], [-0.21, 0.21], [0.21, 0.21], [0.21, -0.21]]

map_type: costmap

obstacle_layer:             #这个名称要和另外两个参数文件中使用的图层名称对应，否则参数无效
  enabled: true             #是否启用该图层
  max_obstacle_height: 0.7  #最大障碍物高度
  min_obstacle_height: 0.0  #最小障碍物高度
  obstacle_range: 2.5       #超过该范围的障碍物，不进行检测
  raytrace_range: 3.0       #在机器人移动过程中，实时清除代价地图上的障碍物的最大范围
  combination_method: 1     #地图代价值更新方式，一般为1
  observation_sources: scan #数据来源可以为多个，空格分开，可以单独指定参数
  track_unknown_space: false 
#如果设置为false，那么地图上代价值就只分为致命碰撞和自由区域两种，
#如果设置为true，那么就分为致命碰撞，自由区域和未知区域三种。
#意思是说假如该参数设置为false的话，就意味着地图上的未知区域也会被认为是可以自由移动的区域，这样在进行全局路径规划时，可以把一些未探索的未知区域也来参与到路径规划。
#不过一般情况未探索的区域不应该当作可以自由移动的区域，因此一般将该参数设置为true。
  origin_z: 0.0             #地图的z原点（以米为单位）
  z_resolution: 0.2         #地图的z分辨率，以米/单元为单位
  z_voxels: 2               #在每个垂直列中，到网格高度的体素数为 z_resolution * z_voxels
  unknown_threshold: 15.0    #列中被视为“已知”的未知单元格的数量, default: ~<name>/z_voxels
  mark_threshold: 0.0       #列中被视为“空闲”的已标记单元格的最大数量
  publish_voxel_map: false  #是否出于可视化目的发布基础体素网格

  scan: #名称和上面"observation_sources"中的对应
      data_type: LaserScan    #传感器数据类型，现在只支持“PointCloud”，“PointCloud2”和“LaserScan”
      topic: scan             #传感器数据话题名
      marking: true           #是否将此传感器数据反映为图中的障碍
      clearing: true          #是否使用传感器数据清除障碍物（当通过激光测量距离时，内部区域被视为没有障碍物）
      inf_is_vaild: true      #当激光检测到无穷大时，扫描阵列中可能包含inf值。是否使用该值（如果设置为true，则inf的值可用于清除障碍物。）
      min_obstacle_height: 0.1 #传感器读数的最小高度（以米为单位）被视为有效
      max_obstacle_height: 0.35 #视为有效的传感器读数的最大高度（以米为单位）
#   bump:
#     data_type: PointCloud2
#     topic: mobile_base/sensors/bumper_pointcloud
#     marking: true
#     clearing: false
#     min_obstacle_height: 0.0
#     max_obstacle_height: 0.15
  # for debugging only, let's you see the entire voxel grid


#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor: 8.0             #衰减因子，越大上面的曲线越陡
  inflation_radius: 0.4                #最大距障碍物的距离
  inflation_unknown:  true
  
static_layer:
  enabled:              true
