global_costmap:
  global_frame: map                     #全局基坐标系
  robot_base_frame: base_link      #机器人坐标系
  update_frequency: 3.0                 #before: 5.0, map更新的频率(单位HZ)
  publish_frequency: 0.5                #before 0.5, map发布的地图显示信息的频率(单位HZ)
  static_map: true                      #是否使用静态地图来初始化代价地图
  transform_tolerance: 0.5              #可忍受的转换（tf）数据延迟，以秒为单位


  cost_scaling_factor: 10.0             #衰减因子，越大上面的曲线越陡
  inflation_radius: 0.6                #最大距障碍物的距离

  plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
