GlobalPlanner:                                  # Also see: http://wiki.ros.org/global_planner
  old_navfn_behavior: false                     # Exactly mirror behavior of navfn, use defaults for other boolean parameters, default false
  use_quadratic: true                           # Use the quadratic approximation of the potential. Otherwise, use a simpler calculation, default true
  use_dijkstra: true                            # Use dijkstra's algorithm. Otherwise, A*, default true
  use_grid_path: false                          # Create a path that follows the grid boundaries. Otherwise, use a gradient descent method, default false
  
  allow_unknown: true                          # Allow planner to plan through unknown space, default true
                                                #Needs to have track_unknown_space: true in the obstacle / voxel layer (in costmap_commons_param) to work
  planner_window_x: 0.0                         # default 0.0
  planner_window_y: 0.0                         # default 0.0
  default_tolerance: 0.2                        # If goal in obstacle, plan to the closest point in radius default_tolerance, default 0.0(当目标点在障碍中，规划允许有一定的容差)

#以下三个参数也决定全局路径规划的性能
  cost_factor: 1.0                              #default 3.0，代价因子
  neutral_cost: 55                              #default 50，中等代价值
  lethal_cost: 253                              #default 253，致命代价值

  publish_potential: true                       #default true ，Publish Potential Costmap (this is not like the navfn pointcloud2 potential)（是否发布costmap的势函数）
  orientation_mode: 0                           #default 0，设置点的方向
  orientation_window_size: 1                    #default 1，根据orientation_mode指定的位置积分确定窗口方向
